# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.


title: "Ulrich Herb - ScholComm & more"
author: "Ulrich Herb"
description: >- # this means to ignore newlines until "baseurl:"
    This is the website of Ulrich Herb, I work for Saarland University, scidecode science consulting and as a freelancer.
    In my blog I discuss issues around scientific publishing and open science.
    If you are interested in an exchange of ideas, cooperation or services that I offer, please do not hesitate to contact  me.  
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ulrichherb.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Email / Social media user names used by the minima theme:
# All of these are optional and can be removed or commented out
email: "u.herb@scidecode.com"
twitter_username: "scinoptica"
# github_username: "githubuser"
linkedin_username: "ulrichherb"
#facebook_username: username
#flickr_username: username
#instagram_username: username
#pinterest_username: username
#youtube_username: username
#googleplus_username: +username


# Build settings
<<<<<<< HEAD
theme: minima
=======
theme: jekyll-theme-tactile
>>>>>>> parent of f534fe5 (Set theme jekyll-theme-minimal)
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
